- hosts: 
    - web
    - db
  tasks:
    - name: pushing file from url to servers
      get_url:
        url: http://www.costtocost.in/list/pricelist.pdf
        dest: /tmp/redhat
      delegate_to: client-2