- name: Example of Playbook level variable
  hosts: web
  vars_prompt:
    - name: username
      prompt: "Plese give your username"
      private: no
 
    - name: pw
      prompt: "Please type of your password"
      private: yes

  tasks:
     - name: add user and apply  password
       user:
           name: "{{ username }}"
           state: present
           password: "{{ pw | password_hash('sha512') }}"